# Generated by Django 5.1.15 on 2026-06-04 16:55

import django.db.models.deletion
import readinglists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_book_isbn_10'),
        ('clinicians', '0004_seed_license_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('share_token', models.CharField(default=readinglists.models.generate_share_token, editable=False, max_length=32, unique=True)),
                ('is_shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='clinicians.clinician')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.book')),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='readinglists.readinglist')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('reading_list', 'book')},
            },
        ),
        migrations.AddField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='reading_lists', through='readinglists.ReadingListItem', to='books.book'),
        ),
    ]
