# Generated by Django 5.1.15 on 2026-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='purpose',
            field=models.TextField(blank=True, default='', help_text='What this list is for — what you hope the reader gets out of it.'),
        ),
    ]
