# Generated by Django 5.1.15 on 2026-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_source_book_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
