# Generated by Django 5.1.15 on 2026-05-31 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='engagement.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
