# Generated by Django 5.1.15 on 2026-05-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='video_bio_url',
            field=models.URLField(blank=True, default='', help_text='Link to a short intro/biography video (YouTube, Vimeo, Loom, etc.).', max_length=500),
        ),
    ]
