# Generated by Django 5.1.15 on 2026-06-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0004_seed_license_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinician',
            name='npi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='clinician',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManualVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_npi', 'No NPI provided'), ('npi_mismatch', 'NPI name mismatch'), ('npi_inactive', 'NPI inactive'), ('other', 'Other')], default='no_npi', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='clinicians.clinician')),
            ],
        ),
    ]
