# Generated by Django 5.1.15 on 2026-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_isbn_10'),
        ('engagement', '0001_initial'),
        ('seekers', '0002_seeker_interests_seeker_saved_clinicians_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='saved_clinicians',
        ),
        migrations.AddField(
            model_name='seeker',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        # M2M `through` can't be added via AlterField — remove the plain M2M, then re-add it
        # pointing at the engagement.SavedBook through model.
        migrations.RemoveField(
            model_name='seeker',
            name='saved_books',
        ),
        migrations.AddField(
            model_name='seeker',
            name='saved_books',
            field=models.ManyToManyField(blank=True, related_name='saved_by_seekers', through='engagement.SavedBook', to='books.book'),
        ),
    ]
