# Generated by Django 5.1.15 on 2026-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0003_remove_seeker_saved_clinicians_seeker_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_images/'),
        ),
    ]
