# Generated by Django 5.1.15 on 2026-05-31 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_book_isbn_10'),
        ('clinicians', '0003_clinician_video_bio_url'),
        ('seekers', '0002_seeker_interests_seeker_saved_clinicians_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('review_viewed', 'Review viewed'), ('review_clicked', 'Review clicked'), ('clinician_viewed', 'Clinician profile viewed'), ('clinician_followed', 'Clinician followed'), ('clinician_unfollowed', 'Clinician unfollowed'), ('book_viewed', 'Book viewed'), ('book_saved', 'Book saved'), ('book_unsaved', 'Book unsaved'), ('search_performed', 'Search performed'), ('affiliate_clicked', 'Affiliate buy-link clicked')], db_index=True, max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.book')),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinicians.clinician')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.review')),
                ('source_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.review')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='engagement__event_t_bdbc75_idx'), models.Index(fields=['session_id', 'created_at'], name='engagement__session_14725d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_edges', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_edges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='engagement_follow_no_self_follow')],
                'unique_together': {('follower', 'followee')},
            },
        ),
        migrations.CreateModel(
            name='SavedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_saves', to='books.book')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_saves', to='seekers.seeker')),
                ('via_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.review')),
            ],
            options={
                'unique_together': {('seeker', 'book')},
            },
        ),
    ]
