# Generated by Django 5.1.15 on 2026-05-30 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicianlicense',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='clinicianspecialty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='clinicianspecialty',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='clinicianlicense',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicians.license'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicianspecialty',
            unique_together={('clinician', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='clinicianlicense',
            unique_together={('clinician', 'license', 'issued_state')},
        ),
    ]
